;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	dt-insert-line-above
  dt-insert-line-below
	))

(setq mc/cmds-to-run-once
      '(
  dt-close-buffer
  dt-new-untitled-buffer
  dt-open-file
  dt-reopen-closed-buffer
	))
